version: '2'
services:
  postgres:
    container_name: clair_db
    image: postgres:latest
    restart: unless-stopped
    networks:
      - clairnet
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_app
    image: quay.io/coreos/clair:latest
    restart: unless-stopped
    networks:
      - clairnet
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]

networks:
    clairnet: